gesdinet_jwt_refresh_token:
    refresh_token_class: Gesdinet\JWTRefreshTokenBundle\Entity\RefreshToken
    ttl: '%env(int:JWT_REFRESH_TTL)%'
    ttl_update: true
    single_use: true
    token_parameter_name: refresh_token
