lexik_jwt_authentication:
    secret_key: /var/jwt/private.pem
    public_key: /var/jwt/public.pem
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: '%env(int:JWT_ACCESS_TTL)%'
    user_id_claim: email
